### ISSUE TITLE
First use of MrDox: configuration

### ISSUE THREAD

**Issue by Becheler** [cppalliance/mrdocs#669]
Hi people,
Amazing job on mrdox ! I'm trying to use it :)
I have the following folder structure:

```
APP [DEV CONTAINER: C++ ...]
├── build
├── docs
├── example
├── mrdox
│   ├── CMakeLists.txt
│   ├── coalescence.cpp
│   ├── config.yaml
│   ├── demography.cpp
│   ├── expressive.cpp
│   ├── geography.cpp
│   └── io.cpp
├── src
├── test
├── CMakeLists.txt
```
Example of a `mrdox/*.cpp` file:

```cpp
#include "quetzal/coalescence.hpp"
int main(){ return 0; }
```
- All `mrdox/*.cpp` files compile fine when running cmake with `export_compile_commands`set to `ON`
- I am not sure what the `config.yaml should be`, especially the `source-root` value ?
- For now I used the documentation one:
```yml
concurrency: 1      # number of threads to use
source-root: ../    # source files relative to the mrdox.yml file
multipage: false    # generate multiple pages
verbose: true       # print verbose output
```
