### ISSUE TITLE
include-symbols: single asterisk doesn't behave as advertised in the docs

### ISSUE THREAD

**Issue by anarthal** [cppalliance/mrdocs#824]
If I understood [this page in the docs](https://www.mrdocs.com/docs/mrdocs/develop/config-file.html#_symbol_filters) correctly, a single asterisk is allowed in `input-filters`, and should match all entities in the namespace, but not sub-namespaces. With this config file:

```yml
source-root: ../include
compilation-database: ./CMakeLists.txt
multipage: true
include-symbols:
  - 'boost::mysql::*'
verbose: true
use-system-libc: true
base-url: https://github.com/boostorg/mysql/blob/master/include/
```

And this code:

```cpp

namespace boost::mysql {

/// Should appear.
struct public_api
{
};

namespace detail {

/// This shouldn't appear
struct private_api
{
};

}  // namespace detail

}  // namespace boost::mysql
```

We have the following output:

```
$> tree reference-output
reference-output/
├── boost
│   ├── mysql
│   │   ├── detail
│   │   │   └── private_api.adoc
│   │   ├── detail.adoc
│   │   └── public_api.adoc
│   └── mysql.adoc
├── boost.adoc
├── index.adoc
└── reference.tag.xml

$> mrdocs --version
MrDocs
    C++ Documentation Tool
    version: 0.0.3
    build: 93d5d102c39b093d402ae3f95302fd734c8de616
    built with LLVM 20.0.0git
```

Interestingly, subsequently nested namespaces don't appear (e.g. `boost::mysql::detail::very_private` doesn't seem to match).
